server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:mysql://turntable.proxy.rlwy.net:35404/railway
    username: root
    password: kcpDgbIlVJrcDqcjyIorToXUubLjqNUr
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none   # Có thể đổi thành 'none' khi deploy chính thức
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect